### ISSUE TITLE
Some events doesn't tell what extension triggered them

### ISSUE THREAD

**Issue by muhakh** [joomla-projects/gsoc16_recording-action-logs#11]
Some events like `onContentAfterSave` has a parameter $context which tells which extension triggered them. Other events like `onUserAfterSave` doesn't tell the extension that triggered it as it's triggered in the `JUser` class.
So, my question is: How can I get the extension that triggered those events?

**Comment by Llewellynvdm** [comment]
You could use

```
$jinput = JFactory::getApplication()->input;
$context = $jinput->get('option');
```

**Comment by muhakh** [comment]
Thanks Llewellyn, It worked very well.
