### ISSUE TITLE
UserLogsHelper::dataToCsv($data)

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/gsoc16_recording-action-logs#47]
### Steps to reproduce the issue

https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/administrator/components/com_userlogs/helpers/userlogs.php#L28-L56
### Expected result

Using JFile or view.<type>.php (see below)
### Actual result

hard coded php function
### Additional comments

Have a look here https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_admin/views/sysinfo

There we have different view.<type>.php that shoud fit the needs.

**Comment by zero-24** [comment]
This way it is easy to introduce json, text etc. and different formats

**Comment by muhakh** [comment]
@zero-24 I think the `view.csv.php` file will work if we are exporting the whole list of logs, but if we want to export selected logs, it won't be useful as the `JToolbarHelper::link` doesn't provide a way to select elements. Is there a way to **export selected logs** using it?

**Comment by zero-24** [comment]
Than we should atleast move that code to JFile classes

**Comment by muhakh** [comment]
I have a problem matching the JFile class with my code. As I just want a temporary file to be created and downloaded without creating a file in the server. Is this possible using JFile?

**Comment by zero-24** [comment]
Maybe this can help https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/views/sysinfo/view.text.php i can have a look into that later today too.
