### ISSUE TITLE
why there is a clean controller in the root 

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/gsoc16_recording-action-logs#49]
### Steps to reproduce the issue

https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/administrator/components/com_userlogs/controller.php
### Expected result

is that expected && needed?
### Actual result

there is a clear controller file

**Comment by muhakh** [comment]
When I remove it, this error occurs 

> **Invalid controller class: UserlogsController**

**Comment by zero-24** [comment]
Ok sorry just checked we do the same for other core components like com_admin.
