### ISSUE TITLE
Where come newsletter_option & newsletter_extensions from?

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/gsoc16_recording-action-logs#50]
### Steps to reproduce the issue

https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/plugins/system/userlogs/userlogs.php#L628-L629
### Actual result

Some code i don't understand

**Comment by muhakh** [comment]
If you mean the code in this line https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/plugins/system/userlogs/userlogs.php#L677
It was a mistake that I fixed here https://github.com/joomla-projects/gsoc16_recording-action-logs/pull/52/files#diff-07f74089cf08f017f2bc9ff63f4f0613R740

**Comment by zero-24** [comment]
Ah correct. Just the wrong link. Thanks
