### ISSUE TITLE
Profiles? in the Plugin Code

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/gsoc16_recording-action-logs#51]
### Steps to reproduce the issue

https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/plugins/system/userlogs/userlogs.php#L628-L629

https://github.com/joomla-projects/gsoc16_recording-action-logs/tree/staging/plugins/system/userlogs/profiles
### Expected result

using a better name
### Actual result

profiles which not fit here.

**Comment by muhakh** [comment]
Is it about the name of the folder/file? or there is something else?

**Comment by zero-24** [comment]
just the name of the folder and file :smile: (as well as in the code)

**Comment by muhakh** [comment]
What do you suggest :smile: ?

**Comment by zero-24** [comment]
forms/userlogs.xml or forms/settings.xml ?
