### ISSUE TITLE
Menu entry for the new component is missing on new install if you install sample data

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/gsoc16_recording-action-logs#60]
### Steps to reproduce the issue
- Downlod the current branch
- Install (using sample data e.g. testing)
- See there is no menu entry for the component
### Expected result

Menu entry for the new component
### Actual result

No menu entry for the new component
### System information (as much as possible)

The menu gots truncated here: https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/installation/sql/mysql/sample_testing.sql#L10

and needs to be refilled here:
https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/installation/sql/mysql/sample_testing.sql#L362

We should also look at the assests table

**Comment by muhakh** [comment]
The `#__menu` and `#__assets` tables are truncated in all sample data files :smile:

**Comment by zero-24** [comment]
Yes to fill it with the needed content for the sample data

**Comment by zero-24** [comment]
Thanks :smile:
